Repository designatucr/designverse2024, pull requests merged in 2023-12, with the labels that each got.

#46 added new logo
  src/components/static/upcoming/Upcoming.jsx
Labels: Ready to Review

#51 Merge
  .github/workflows/sync-template.yaml
  cypress/component/admin/Dropdown.cy.jsx
  cypress/component/admin/dashboards/Toolbar.cy.jsx
  cypress/e2e/admin/participants/Sort.cy.js
  cypress/fixtures/participants.json
  src/app/api/judging/route.js
  src/app/api/participants/route.js
  src/app/api/prizes/route.js
  src/app/page.js
  src/app/user/join/[teamID]/page.js
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/Select.jsx
  src/components/dynamic/admin/dashboards/Toolbar.jsx
  src/components/dynamic/admin/services/DropDown.jsx
  src/components/dynamic/admin/services/Dropdown.jsx
  src/components/dynamic/admin/services/Toolbar.jsx
  src/components/dynamic/admin/services/calendar/Modal.jsx
  src/components/dynamic/admin/services/checkin/CheckIn.jsx
  src/components/dynamic/admin/services/judging/Toolbar.jsx
  src/components/dynamic/form/Feedback.jsx
  src/components/dynamic/form/Participant.jsx
  src/components/dynamic/form/Questions.jsx
  src/components/dynamic/user/Team.jsx
  src/data/Releases.js
  src/data/dynamic/Navigation.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Volunteers.js
Labels: repository

#50 Postponed release dates
  src/data/Releases.js
Labels: bug, Ready to Review

#37 fixed forms data
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
  src/data/dynamic/form/Interest.js
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Volunteers.js
Labels: Do Not Merge, forms

#53 stylin the form
  cypress/component/admin/Button.cy.jsx
  src/components/dynamic/Button.jsx
  src/components/dynamic/Input.jsx
  src/components/dynamic/Radio.jsx
  src/components/dynamic/Select.jsx
  src/components/dynamic/form/Form.jsx
  src/components/dynamic/form/Questions.jsx
  src/components/dynamic/form/Upload.jsx
  src/data/dynamic/Button.js
  tailwind.config.js
Labels: Do Not Merge

#59 added lily animation
  src/components/static/upcoming/Upcoming.jsx
  tailwind.config.js
Labels: enhancement, coming soon, Ready to Review

#60 form data bugs
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Volunteers.js
Labels: bug

#62 maxed width
  src/components/dynamic/ProtectedPage.jsx
Labels: Ready to Review

#64 changed form color and text bold
  src/components/dynamic/Input.jsx
  src/components/dynamic/ProtectedPage.jsx
  src/components/dynamic/Radio.jsx
  src/components/dynamic/Select.jsx
  src/components/dynamic/form/Form.jsx
  src/components/dynamic/form/Questions.jsx
  src/components/dynamic/form/Textarea.jsx
  src/components/dynamic/form/Upload.jsx
Labels: bug, Ready to Review, forms

#72 added animation
  src/components/static/Apply.jsx
  src/components/static/Countdown.jsx
  src/components/static/upcoming/Upcoming.jsx
  tailwind.config.js
Labels: Ready to Review

#70 Stormyy00/tagg
  cypress/component/admin/Filters.cy.jsx
  cypress/component/admin/dashboards/Toolbar.cy.jsx
  cypress/e2e/admin/admins/Filter.cy.js
  cypress/e2e/admin/committees/Filter.cy.js
  cypress/e2e/admin/judges/Filter.cy.js
  cypress/e2e/admin/mentors/Filter.cy.js
  cypress/e2e/admin/participants/Filter.cy.js
  cypress/e2e/admin/sponsors/Filter.cy.js
  cypress/e2e/admin/teams/Filter.cy.js
  cypress/e2e/admin/volunteers/Filter.cy.js
  src/components/dynamic/admin/Filters.jsx
  src/components/dynamic/admin/Input.jsx
  src/components/dynamic/admin/Tag.jsx
  src/data/dynamic/Tags.js
  src/data/dynamic/admin/Admins.js
  src/data/dynamic/admin/Committees.js
  src/data/dynamic/admin/Judges.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Participants.js
  src/data/dynamic/admin/Sponsors.js
  src/data/dynamic/admin/Teams.js
  src/data/dynamic/admin/Volunteers.js
  tailwind.config.js
Labels: Ready to Review

#78 New coming soon
  public/svgs/Bear.svg
  public/svgs/BigLogo.svg
  public/svgs/animals.svg
  public/svgs/logo.svg
  public/svgs/mushrooms2.svg
  src/components/dynamic/form/Form.jsx
  src/components/static/Apply.jsx
  src/components/static/Countdown.jsx
  src/components/static/upcoming/Upcoming.jsx
  tailwind.config.js
Labels: coming soon

#80 Fix Navbar and Protected Page
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/ProtectedPage.jsx
Labels: Ready to Review

#83 Ordering
  src/app/api/mentors/route.js
  src/data/dynamic/admin/Mentors.js
  src/data/dynamic/admin/Volunteers.js
  src/data/dynamic/form/Information.js
Labels: Ready to Review

#84 Add About Us Section
  public/svgs/mushroomWithLeaves.svg
  src/components/static/About.jsx
  src/components/static/upcoming/Upcoming.jsx
Labels: Ready to Review

#85 Add Footer
  public/svgs/mushroomsFooterLeft.svg
  public/svgs/mushroomsFooterRight.svg
  public/svgs/whiteLogo.svg
  src/components/static/Footer.jsx
  src/components/static/upcoming/Upcoming.jsx
Labels: Ready to Review

#86 Add FAQ
  src/components/static/FAQ.jsx
  src/components/static/Footer.jsx
  src/components/static/Item.jsx
  src/components/static/upcoming/Upcoming.jsx
  src/data/static/FAQ.js
Labels: Ready to Review

#91 Fuyuki/404 Styled 404 Page
  src/components/dynamic/Error.jsx
Labels: Ready to Review

#95 loading
  src/components/dynamic/Loading.jsx
Labels: Do Not Merge

#101 Forms Cleanup
  public/files/DesignVerseCodeofConduct.pdf
  public/files/DesignVerseSponsorshipPacket.pdf
  src/components/dynamic/form/Questions.jsx
  src/data/Config.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
Labels: Ready to Review

#104 Add Page Title
  src/app/page.js
Labels: Ready to Review

#105 added sponsor form reasons
  src/data/dynamic/form/Sponsors.js
Labels: forms

#108 Release About, FAQ, Footer
  src/components/static/About.jsx
  src/components/static/Footer.jsx
  src/components/static/upcoming/Upcoming.jsx
Labels: Ready to Review
