Repository designatucr/designverse2024, pull requests merged in 2024-01, with the labels that each got.

#113 responsive Ab/Us
  src/components/static/About.jsx
Labels: Ready to Review

#126 Fuyuki/ProfileComponent
  src/components/static/Profile.jsx
Labels: Ready to Review

#139 added waves to FAQ background
  public/svgs/waves.svg
  src/components/static/FAQ.jsx
Labels: FAQ

#138 Overlap issue Footer Redesign
  public/svgs/ActualFooterLand.svg
  public/svgs/FooterWithoutEmoji.svg
  src/components/static/Footer.jsx
  src/components/static/live/Live.jsx
  src/components/static/postlive/Postlive.jsx
  src/data/Releases.js
Labels: bug, Do Not Merge

#131 Stormyy00/tracks
  public/svgs/tracks/left.svg
  public/svgs/tracks/middle.svg
  public/svgs/tracks/right.svg
  public/svgs/wave.svg
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/form/form/Form.jsx
  src/components/static/Tracks.jsx
  src/components/static/upcoming/Upcoming.jsx
Labels: Ready to Review

#151 About Component height adjusted and changed to relative
  src/components/dynamic/Navigation.jsx
  src/components/static/About.jsx
  src/components/static/FAQ.jsx
Labels: Ready to Review

#136 support us section
  src/components/static/FAQ.jsx
  src/components/static/Support.jsx
  src/components/static/upcoming/Upcoming.jsx
  tailwind.config.js
Labels: coming soon, Do Not Merge

#155 Leads Component
  src/components/static/Leads.jsx
  src/components/static/Profile.jsx
  src/components/static/upcoming/Upcoming.jsx
Labels: Ready to Review
