Repository designatucr/designverse2024, pull requests merged in 2024-02, with the labels that each got.

#165 Committee Page
  public/svgs/tracks/track1Back.svg
  public/svgs/tracks/track1Front.svg
  public/svgs/tracks/track2Back.svg
  public/svgs/tracks/track2Front.svg
  public/svgs/tracks/track3Back.svg
  public/svgs/tracks/track3Front.svg
  public/svgs/tracks/track4Back.svg
  public/svgs/tracks/track4Front.svg
  src/components/static/Committees.jsx
  src/components/static/TrackCards.jsx
  src/components/static/Tracks.jsx
  src/components/static/upcoming/Upcoming.jsx
  src/data/static/Committees.js
Labels: Ready to Review, Pre-Live/Live

#177 Menthy/track
  public/svgs/sponsorTop.svg
  public/svgs/tracks/track3Back.svg
  src/components/static/Sponsors.jsx
  src/components/static/TrackCards.jsx
  src/components/static/Tracks.jsx
  src/data/static/Tracks.js
  tailwind.config.js
Labels: Ready to Merge

#160 Fardinzam/schedule section2
  public/svgs/schedule/temp.svg
  public/svgs/schedule/wave.svg
  src/components/dynamic/Schedule.jsx
  src/components/static/About.jsx
  src/components/static/Committees.jsx
  src/components/static/Leads.jsx
  src/components/static/Link.jsx
  src/components/static/Profile.jsx
  src/components/static/Resource.jsx
  src/components/static/Sponsors.jsx
  src/components/static/Support.jsx
  src/components/static/Supports.jsx
  src/components/static/TrackCards.jsx
  src/components/static/Tracks.jsx
  src/components/static/upcoming/Upcoming.jsx
  src/data/MockSchedule.js
  src/data/static/Committees.js
  tailwind.config.js
Labels: Ready to Review, Pre-Live/Live, Schedule

#169 Responsive Footer
  src/components/static/Footer.jsx
Labels: Ready to Review

#156 created navbar
  package-lock.json
  package.json
  public/svgs/landing/mushroomWithLeaves.svg
  public/svgs/river.svg
  public/svgs/schedule/temp.svg
  public/svgs/sponsors/avgpc.jpg
  public/svgs/sponsors/design.jpg
  public/svgs/sponsors/notion.jpg
  public/svgs/sponsors/redbull.jpg
  public/svgs/sponsors/ucr.jpg
  src/components/dynamic/Schedule.jsx
  src/components/static/About.jsx
  src/components/static/FAQ.jsx
  src/components/static/Leads.jsx
  src/components/static/Navigation.jsx
  src/components/static/Resource.jsx
  src/components/static/Sponsors.jsx
  src/components/static/Tracks.jsx
  src/components/static/upcoming/Upcoming.jsx
  src/data/static/Committees.js
  src/data/static/Nav.js
Labels: Do Not Merge

#190 fix typo in sync template workflow
  .github/workflows/sync-template.yaml
Labels: repository, Ready to Review
